### ISSUE TITLE
一点击动漫就会闪退

### ISSUE THREAD

**Issue by ljy5201314** [lanlinju/Anime#1]
最新版的app出现闪退，安卓版本是12

**Comment by Lanlinju** [comment]
刚刚测试了一下，原因应该是新版本与旧版本不兼容，数据库方面改动没做兼容升级，可以尝试以下两种方式解决：
第一种：清除应用的全部数据
第二种：卸载当前版本重新安装

**Comment by ljy5201314** [comment]
> 刚刚测试了一下，原因应该是新版本与旧版本不兼容，数据库方面改动没做兼容升级，可以尝试以下两种方式解决： 第一种：清除应用的全部数据 第二种：卸载当前版本重新安装
卸载重新安装后可以了，感谢
