### ISSUE TITLE
TV端页面显示异常

### ISSUE THREAD

**Issue by kkbox88755** [lanlinju/Anime#14]
新版本(v1.2.2）在TV端浏览时无法顺利选到搜寻页面，当要尝试让光标移动到搜寻或设置等顶部button的时候页面就会乱跳。
此问题在1.2.1版时没有发生，不确定是否是因直接从2.1更新到2.2造成的。

**Comment by lanlinju** [comment]
是在Week页面上最顶部一排Button吗，奇怪的是我这里测试正常，估计是最近升级SDK35和Material3版本导致的，我将会构建一个未升级前的版本用来测试，也可以先尝试卸载重装一下

**Comment by kkbox88755** [comment]
是的，是Week上面那排，此外在Favourite页面也会乱跳
乱跳的页面似乎是与Home页面重叠

**Comment by lanlinju** [comment]
这个是未升级相关依赖时的版本，
[Anime-v1.2.1-release.zip](https://github.com/user-attachments/files/17068984/Anime-v1.2.1-release.zip)
顺便帮忙测试一下这个AndroidTV[兼容版](https://github.com/lanlinju/Anime/releases/tag/v1.2.1)(文件名包含TV的apk)，另外选中Favourite时会跳至Home，让我有点怀疑是不是导航组件没有升级的缘故，稍后我也会构建一个升级导航依赖后的版本

**Comment by lanlinju** [comment]
下面的是升级导航依赖后的版本
[Anime-v1.2.2-upgrade-navigation.zip](https://github.com/user-attachments/files/17069430/Anime-v1.2.2-upgrade-navigation.zip)

**Comment by kkbox88755** [comment]
三个版本都试了，除了1.2.1可以正常使用，另外两个1.2.2都会乱跳

**Comment by lanlinju** [comment]
估计就是升级SDK35或者Material版本导致的，目前先使用测试发的1.2.1版本过度吧，这个和最新版功能一致，除了版本号和一些依赖的版本

**Comment by lanlinju** [comment]
Hi, @kkbox88755  有关页面异常跳动的问题在AndroidTV兼容版中得到了解决，具体的原因是由于`HorizontalPager`引起的，其中的参数`userScrollEnabled = false`只能屏蔽滑动手势切换页面，但是并不能阻止由于焦点移动引起的嵌套滚动，这个是兼容版的[地址](https://github.com/lanlinju/Anime/issues/13#issuecomment-2373057274)

**Comment by kkbox88755** [comment]
目前测试都正常了，非常感谢🙏
