### ISSUE TITLE
一些请求

### ISSUE THREAD

**Issue by nathanlcl** [Lanlinju/Anime#2]
1.希望添加对首页顶部图片、软件主题色的自定义修改
2.希望开屏图标是圆的（个人感觉方形太僵硬）
3.希望首页顶部文字显示的是当前使用的动漫源的中文全称
4.希望可以修改下载文件的存储位置
5.希望添加对AGE动漫源的支持（官方软件有广告）

感谢作者！！！

**Comment by Lanlinju** [comment]
非常感谢反馈，不过下面可能是一些不太令人满意的回答：
1. 有关自定义首页顶部图片和主题，这个以后可能会添加
2. 有关开屏图标是方的，这个可能和手机型号和系统版本相关，有的显示圆角、方角或者圆形图标
3. 有关主页标题显示动漫源名称。因为动漫时间表下面有个当前动漫源信息，感觉重复，目前不考虑加上
4. 有关修改下载文件位置，这个大概率不会加，目前安卓对存储位置限制比较严格，涉及权限申请(不太想申请过多权限)
5. 有关新增动漫源，目前并没有打算，以后可能会(主要不太擅长爬取数据)
