### ISSUE TITLE
使用代理就进不去

### ISSUE THREAD

**Issue by youlan2333** [lanlinju/Anime#4]
![Screenshot_20240731-095218.png](https://github.com/user-attachments/assets/b1990929-3645-4230-a214-66f04b9abc46)

**Comment by lanlinju** [comment]
建议关闭代理使用，或者选择动漫源Yhdm、Agedm、Anfuns这三个可以在代理情况下正常访问，目前具体原因并不清楚，可能是和数据源本身有关。

**Comment by youlan2333** [comment]
> 建议关闭代理使用，或者选择动漫源Yhdm、Agedm、Anfuns这三个可以在代理情况下正常访问，目前具体原因并不清楚，可能是和数据源本身有关。

经测试这两个进不去![Screenshot_20240801-151616~2.png](https://github.com/user-attachments/assets/d733d0d4-1a7c-46af-b452-48c6587a03cb)

**Comment by lanlinju** [comment]
应该是和数据源本身相关，有些需要挂代理才能访问，有些则相反 挂代理反而不能访问，我这里的访问情况目前为：
1. 仅不开代理可以访问：Silisili, Girigiri, Mxdm
2. 开代理才可以访问：Yhdm, Anfuns
3. 开不开代理都可以：Age

**Comment by youlan2333** [comment]
> 应该是和数据源本身相关，有些需要挂代理才能访问，有些则相反 挂代理反而不能访问，我这里的访问情况目前为：
> 1. 仅不开代理可以访问：Silisili, Girigiri, Mxdm
> 2. 开代理才可以访问：Yhdm, Anfuns
> 3. 开不开代理都可以：Age

是这样，悲
