### ISSUE TITLE
源都失效了


### ISSUE THREAD

**Issue by 3100451140** [lanlinju/Anime#6]

**Comment by lanlinju** [comment]
可以尝试修改Silisili的域名为： https://www.silisilifun.com/
还有部分动漫源需要开代理才能访问
![Screenshot_2024-08-05-22-44-30-380_com sakura anime](https://github.com/user-attachments/assets/903186eb-2d48-48a0-87eb-9fc7f26c38d9)

**Comment by 3100451140** [comment]
好了，又能用了♪(^∇^*)

**Comment by lanlinju** [comment]
发现昨天那个需要挂代理访问，
![Screenshot_2024-08-06-13-04-09-005_com microsoft emmx-edit](https://github.com/user-attachments/assets/1a73d772-6d9b-44f1-9030-2f3513e46140)
下面两个不需要：
https://www.silisili.link （默认域名）
https://www.sssfun.cc
