### ISSUE TITLE
大佬  能加入国漫吗？

### ISSUE THREAD

**Issue by zhusonger** [lanlinju/Anime#7]
哈喽 我看silisili追番里有国漫 能也加上吗？

**Comment by zhusonger** [comment]
![image](https://github.com/user-attachments/assets/00a0f407-57ec-49b4-a301-1cdff4702524)
PC版本页面他这里有2个节点 可以遍历一下

**Comment by zhusonger** [comment]
![image](https://github.com/user-attachments/assets/2e713c94-f7f8-4502-8d2f-995b698a592c)
这里判断下weekElements的个数

**Comment by lanlinju** [comment]
你好，我测试了一下，你的想法是可行的，
![3bf678c7f7fc88a33c39d4cd182d85b9](https://github.com/user-attachments/assets/28d4ef2c-8cab-4ccd-beae-85cee2c7b771)
只不过加上国漫之后，列表看起来有点长
![eae405f9f43d672266f4b1b8778dbd52](https://github.com/user-attachments/assets/fffea3cf-4afa-492d-92a5-a321ca312056)

**Comment by zhusonger** [comment]
嗯嗯 我是长点无所谓 至少可以找到
觉得丑的话 建议跟pc的网页一样 分2个分栏

**Comment by zhusonger** [comment]
不急不急 刚发现你这个app 用的时候 提个建议而已 大佬慢慢来
