### ISSUE TITLE
TV版播放时无法使用遥控器

### ISSUE THREAD

**Issue by kkbox88755** [lanlinju/Anime#9]
目前Android TV在播放时无法透过遥控器进行暂停/播放（ok键）、快进（左键、右键）等操作，未来会考虑新增吗？

**Comment by lanlinju** [comment]
Hi，我现在已经实现了几个遥控器功能，但是都是在模拟器上进行测试的(Android TV真机理论可行)，所以可以帮忙在Android TV真机测试一下吗，
[Anime-v1.2.0-TV-Test.zip](https://github.com/user-attachments/files/16739527/Anime-v1.2.0-TV-Test.zip)(需要解压后安装)
遥控器功能如下：
1. 确定键(OK键): 暂停/播放视频
2. 方向左键、右键：分别是后退15s和快进15s
3. 方向上键: 打开选集列表(按返回键关闭)
4. 方向下键: 播放下一剧集

**Comment by kkbox88755** [comment]
在Android TV 11测试以上功能都可正常使用，谢谢！

**Comment by lanlinju** [comment]
这个是用于测试的第二版，主要增加了对宽屏设备的适配：
[Anime-v1.2.0-Test-TV-2.zip](https://github.com/user-attachments/files/16749163/Anime-v1.2.0-Test-TV-2.zip)

下面是问题解决情况：
1. 收藏页面的控制问题，我这里现在测试正常，(不可以操作可以继续反馈)
2. 搜索页面问题做了适配，应该已经解决
3. 资讯页选集问题已经优化，(包括视频播放页面的选集列表)
4. 问题4，5应该是数据源本身有关，未来可能会加上失败重试功能

**Comment by kkbox88755** [comment]
目前在Android TV测试基本没什么问题了，非常感谢作者迅速修复问题🙏

**Comment by lanlinju** [comment]
不用客气，感谢帮忙测试，正式版不久就会发布
